// Regression tests for `devsite init`, spawn-based because init.ts runs on
// import; in-process coverage arrives with the run() split (#9).
// DEVSITE_CADDYFILE points every run at a scratch file so no test ever reads
// or races the machine-global Caddyfile.
import { expect, test } from "bun:test";
import { spawnSync } from "node:child_process";
import { mkdirSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const INIT = join(import.meta.dir, "..", "src", "init.ts");

function devsite(args: string[], opts: { cwd?: string; caddyfile?: string } = {}) {
  const r = spawnSync("bun", [INIT, ...args], {
    cwd: opts.cwd,
    encoding: "utf8",
    env: {
      ...process.env,
      DEVSITE_CADDYFILE: opts.caddyfile ?? join(mkdtempSync(join(tmpdir(), "devsite-none-")), "Caddyfile"),
    },
  });
  return { status: r.status, stdout: r.stdout, stderr: r.stderr };
}

function makeRepo(host = "web.test.internal") {
  const repo = mkdtempSync(join(tmpdir(), "devsite-repo-"));
  mkdirSync(join(repo, "apps", "web"), { recursive: true });
  writeFileSync(
    join(repo, "apps", "web", "package.json"),
    JSON.stringify({ name: "web", devSite: { host } }),
  );
  return repo;
}

function makeCaddyfile(content: string) {
  const p = join(mkdtempSync(join(tmpdir(), "devsite-caddy-")), "Caddyfile");
  writeFileSync(p, content);
  return p;
}

// --- subcommand guard: nothing but `init` may reach the privileged bootstrap ---

test("bare run prints usage and exits 1", () => {
  const r = devsite([]);
  expect(r.status).toBe(1);
  expect(r.stderr).toContain("Usage: devsite init");
});

test("--help does not reach the bootstrap", () => {
  const r = devsite(["--help"]);
  expect(r.status).toBe(1);
  expect(r.stderr).toContain("Usage: devsite init");
});

test("unknown subcommand prints usage and exits 1", () => {
  const r = devsite(["uninstall"]);
  expect(r.status).toBe(1);
  expect(r.stderr).toContain("Usage: devsite init");
});

test("init passes the guard: no routes in cwd exits 1 with the discovery error", () => {
  const empty = mkdtempSync(join(tmpdir(), "devsite-empty-"));
  const r = devsite(["init"], { cwd: empty });
  expect(r.status).toBe(1);
  expect(r.stderr).toContain("No package.json#devSite routes");
});

test("init --dry-run renders the managed region and touches nothing", () => {
  const r = devsite(["init", "--dry-run"], { cwd: makeRepo() });
  expect(r.status).toBe(0);
  expect(r.stdout).toContain("--dry-run: would write");
  expect(r.stdout).toContain("web.test.internal {");
  expect(r.stdout).toContain(">>> devsite v1");
});

test("a host that is not a plain hostname is rejected at discovery", () => {
  const r = devsite(["init", "--dry-run"], { cwd: makeRepo("a.internal; touch pwned") });
  expect(r.status).toBe(1);
  expect(r.stderr).toContain("is not a plain hostname");
  expect(r.stderr).toContain("a.internal; touch pwned");
});

// --- Caddyfile ownership: content outside the managed region is sacred ---

test("pre-existing non-devsite content is never deleted (Homebrew default shape)", () => {
  const caddyfile = makeCaddyfile('# Welcome to Caddy!\n\n:80 {\n\trespond "hi"\n}\n');
  const r = devsite(["init", "--dry-run"], { cwd: makeRepo(), caddyfile });
  expect(r.status).toBe(0);
  // A unified diff always shows deletions as `-` lines; their absence proves survival.
  expect(r.stdout).not.toContain("-:80");
  expect(r.stdout).not.toContain('-\trespond "hi"');
  expect(r.stdout).toContain(">>> devsite v1");
});

test("pre-region (v0) devsite files migrate: other repos' blocks are kept", () => {
  const caddyfile = makeCaddyfile(
    [
      "# Generated by `devsite init` — do not edit by hand.",
      "# Change a project's package.json#devSite and re-run `devsite init`.",
      "",
      "{",
      "\tstorage file_system {",
      '\t\troot "/somewhere"',
      "\t}",
      "\tlocal_certs",
      "}",
      "",
      "# otherproj",
      "other.internal {",
      '\trespond "devsite: dev server for other.internal is not running (start it with bun dev)" 503',
      "}",
      "",
    ].join("\n"),
  );
  const r = devsite(["init", "--dry-run"], { cwd: makeRepo(), caddyfile });
  expect(r.status).toBe(0);
  expect(r.stdout).toContain("1 block(s) from other repos kept");
  // The old file's global block is devsite's own — nothing foreign to keep.
  expect(r.stdout).not.toContain(">>> kept");
});

test("re-running against devsite's own output is a no-op", () => {
  const repo = makeRepo();
  const first = devsite(["init", "--dry-run"], { cwd: repo });
  expect(first.status).toBe(0);
  // Reconstruct the rendered file from the diff's added lines (fresh file → all `+`).
  const content = first.stdout
    .split("\n")
    .filter((l) => l.startsWith("+") && !l.startsWith("+++"))
    .map((l) => l.slice(1))
    .join("\n");
  const caddyfile = makeCaddyfile(`${content}\n`);
  const again = devsite(["init", "--dry-run"], { cwd: repo, caddyfile });
  expect(again.status).toBe(0);
  expect(again.stdout).toContain("already up to date");
});

test("a foreign global options block is merged into the region with a warning", () => {
  const caddyfile = makeCaddyfile(
    '{\n\temail den@example.com\n}\n\n:8080 {\n\trespond "ok"\n}\n',
  );
  const r = devsite(["init", "--dry-run"], { cwd: makeRepo(), caddyfile });
  expect(r.status).toBe(0);
  expect(r.stderr).toContain("global options block");
  expect(r.stdout).toContain(">>> kept");
  expect(r.stdout).not.toContain("-:8080");
});
