#!/usr/bin/env bun
/**
 * devsite init — one-time machine bootstrap for *.internal dev URLs over Tailscale.
 *
 * Design notes:
 *   - No ports. `package.json#devSite` declares only a host; the Caddyfile gets a
 *     `respond 503` placeholder per host, and the devsite Vite plugin (vite.mjs)
 *     swaps in a live `reverse_proxy` to a free ephemeral port at `bun dev` time
 *     via Caddy's admin API. Any number of projects can run at once.
 *   - The Caddyfile is machine-global and several repos register routes into it,
 *     so blocks whose host this repo doesn't own are kept verbatim instead of
 *     being regenerated away.
 *
 * Owns the privileged Caddy setup so nobody has to assemble it by hand. It:
 *   - generates /opt/homebrew/etc/Caddyfile from every workspace package.json#devSite,
 *   - pins Caddy's PKI storage to a fixed path so the local CA is identical no matter
 *     which user runs Caddy (a root service vs a foreground process) — the drift that
 *     silently broke phone cert-trust after a restart,
 *   - widens the internal leaf lifetime so certs don't lapse overnight,
 *   - runs Caddy as the always-on brew service.
 *
 * Run it as yourself (NOT via sudo) — it shells out to sudo only for the privileged
 * steps, so the password prompt lands in your terminal:
 *   bun run devsite init            # apply (prompts for sudo once)
 *   bun run devsite init --dry-run  # print what it would write; touch nothing
 *
 * `bun dev` never needs sudo: it only ever talks to Caddy's admin API on localhost.
 */
import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { homedir, tmpdir } from "node:os";
import { join } from "node:path";

const CADDYFILE = "/opt/homebrew/etc/Caddyfile";
const LEAF_LIFETIME = "168h"; // 7d — survives nights/weekends; Caddy renews it while running.

// Installed under node_modules, so the repo root is where the CLI is invoked.
const repoRoot = process.cwd();
const storageRoot = join(homedir(), "Library", "Application Support", "Caddy");
const caRootCert = join(storageRoot, "pki", "authorities", "local", "root.crt");

// Only `init` exists; anything else (bare run, --help, a typo) must not reach
// the privileged bootstrap.
if (process.argv[2] !== "init") {
  console.error("Usage: devsite init [--dry-run]");
  process.exit(1);
}

const dryRun = process.argv.includes("--dry-run");

type Route = { host: string; project: string };

async function discoverRoutes(): Promise<Route[]> {
  const routes: Route[] = [];
  for (const dir of ["apps", "packages"]) {
    const base = join(repoRoot, dir);
    if (!existsSync(base)) continue;
    for (const rel of new Bun.Glob("*/package.json").scanSync(base)) {
      const pkg = (await Bun.file(join(base, rel)).json()) as {
        name?: string;
        devSite?: { host?: string };
      };
      const host = pkg.devSite?.host;
      if (host) routes.push({ host, project: pkg.name ?? rel });
    }
  }
  return routes.sort((a, b) => a.host.localeCompare(b.host));
}

// Site blocks in the existing (generated) Caddyfile owned by other repos, kept
// verbatim. Blocks start at column 0 as `# <project>\n<host> {` — the global
// options block's lines are tab-indented, so they can't match.
function foreignBlocks(ownHosts: Set<string>): string[] {
  if (!existsSync(CADDYFILE)) return [];
  const existing = readFileSync(CADDYFILE, "utf8");
  const blocks: string[] = [];
  for (const m of existing.matchAll(/^# .+\n(\S+) \{\n[\s\S]*?\n\}/gm)) {
    const [block, host] = m;
    if (host && !ownHosts.has(host)) blocks.push(block);
  }
  return blocks;
}

function renderCaddyfile(routes: Route[], kept: string[]): string {
  const header = [
    "# Generated by `devsite init` — do not edit by hand.",
    "# Change a project's package.json#devSite and re-run `devsite init`.",
    "",
    "{",
    "\t# Pin PKI storage so Caddy's local CA is the SAME no matter which user runs",
    "\t# it (always-on root service vs a foreground process). Every device trusts",
    `\t# this one CA root: ${caRootCert}`,
    "\tstorage file_system {",
    `\t\troot "${storageRoot}"`,
    "\t}",
    "\tlocal_certs",
    "}",
  ].join("\n");

  // Placeholder only — the devsite Vite plugin swaps in a reverse_proxy to the
  // dev server's ephemeral port at runtime via the admin API.
  const blocks = routes.map((r) =>
    [
      "",
      `# ${r.project}`,
      `${r.host} {`,
      "\ttls {",
      "\t\tissuer internal {",
      `\t\t\tlifetime ${LEAF_LIFETIME}`,
      "\t\t}",
      "\t}",
      `\trespond "devsite: dev server for ${r.host} is not running (start it with bun dev)" 503`,
      "}",
    ].join("\n"),
  );

  return `${header}\n${blocks.join("\n")}\n${kept.map((b) => `\n${b}\n`).join("")}`;
}

function run(cmd: string, args: string[], capture = false) {
  const r = spawnSync(cmd, args, {
    stdio: capture ? ["ignore", "pipe", "pipe"] : "inherit",
    encoding: "utf8",
  });
  return { status: r.status ?? 1, out: (r.stdout ?? "").trim() };
}

function sudo(args: string[]) {
  console.log(`  sudo ${args.join(" ")}`);
  if (run("sudo", args).status !== 0) {
    throw new Error(`\`sudo ${args.join(" ")}\` failed`);
  }
}

function applyPrivileged(content: string) {
  const tmp = join(tmpdir(), `Caddyfile.devsite.${process.pid}`);
  writeFileSync(tmp, content);
  if (existsSync(CADDYFILE)) sudo(["cp", CADDYFILE, `${CADDYFILE}.bak`]);
  sudo(["cp", tmp, CADDYFILE]);
  sudo(["chmod", "644", CADDYFILE]);
  run("sudo", ["pkill", "-x", "caddy"]); // kill any non-service foreground Caddy; ok if none
  sudo(["brew", "services", "restart", "caddy"]);
  // Trust the pinned CA in the Mac keychain. Caddy's own auto-trust needs an
  // interactive prompt it can't get as a background service, so do it explicitly.
  console.log("  sudo caddy trust");
  run("sudo", ["caddy", "trust"]); // best-effort; ok if already trusted
}

function tailscale(args: string[]): string | null {
  for (const bin of ["/Applications/Tailscale.app/Contents/MacOS/Tailscale", "tailscale"]) {
    const r = run(bin, args, true);
    if (r.status === 0) return r.out;
  }
  return null;
}

function check(ok: boolean, label: string, detail = "") {
  console.log(`  ${ok ? "✓" : "✗"} ${label}${detail ? ` — ${detail}` : ""}`);
}

function sha256Fp(opensslOut: string): string | null {
  return opensslOut.split("=")[1]?.trim() ?? null;
}

function servedIntermediateFp(host: string): string | null {
  const r = run(
    "bash",
    [
      "-c",
      `echo | openssl s_client -connect ${host}:443 -servername ${host} -showcerts 2>/dev/null ` +
        `| awk '/BEGIN CERT/{n++} n==2{print}' | openssl x509 -noout -fingerprint -sha256 2>/dev/null`,
    ],
    true,
  );
  return r.status === 0 ? sha256Fp(r.out) : null;
}

function pinnedIntermediateFp(): string | null {
  const p = join(storageRoot, "pki", "authorities", "local", "intermediate.crt");
  if (!existsSync(p)) return null;
  const r = run("openssl", ["x509", "-in", p, "-noout", "-fingerprint", "-sha256"], true);
  return r.status === 0 ? sha256Fp(r.out) : null;
}

function verify(routes: Route[]) {
  const host = routes[0]?.host;
  if (!host) return;
  // curl on macOS uses its own trust store, not the keychain devices trust, so
  // check reachability with -k and verify trust separately via the cert chain.
  // Any HTTP status counts: with no dev server running the placeholder answers
  // 503; the Vite plugin swaps in the real upstream at `bun dev` time.
  const code = run(
    "bash",
    ["-c", `curl -k -sS -o /dev/null -w '%{http_code}' --max-time 8 https://${host}/`],
    true,
  ).out;
  check(Boolean(code), `https://${host} answers over TLS (Caddy up)`, `HTTP ${code || "—"}`);

  const served = servedIntermediateFp(host);
  const pinned = pinnedIntermediateFp();
  check(
    Boolean(served && pinned && served === pinned),
    "served cert chains to the pinned CA (what every trusting device sees)",
    served && pinned ? (served === pinned ? "match" : "MISMATCH") : "could not compare",
  );

  const tsIp = tailscale(["ip", "-4"])?.split("\n")[0]?.trim();
  check(Boolean(tsIp), "Tailscale up on this Mac", tsIp ?? "tailscale not reachable");
  if (tsIp) {
    const answered = run("dig", ["+short", "+time=3", "+tries=1", `@${tsIp}`, host], true).out;
    check(
      answered === tsIp,
      "dnsmasq answers on the Tailscale IP (the phone's DNS path)",
      answered || "no answer",
    );
  }
  check(
    existsSync("/etc/resolver/internal"),
    "/etc/resolver/internal present (Mac resolves *.internal locally)",
  );
  check(
    existsSync(caRootCert),
    "local CA root exists (this is what devices must trust)",
    caRootCert,
  );
}

function printChecklist(routes: Route[]) {
  console.log("\nManual, per-device (one-time — can't be automated from here):");
  console.log(
    `  • Tailscale admin → DNS → split-DNS: domain 'internal' → this Mac's Tailscale IP.`,
  );
  console.log(
    `  • On each phone: install AND trust the CA root, then reload https://${routes[0]?.host}`,
  );
  console.log(`      ${caRootCert}`);
  console.log(`      (iOS: install the profile, THEN Settings → General → About →`);
  console.log(`       Certificate Trust Settings → toggle it ON — installing ≠ trusting.)`);
  console.log("\nFrom here on your only surface is `bun dev` — it needs no sudo.");
}

async function main() {
  const routes = await discoverRoutes();
  if (routes.length === 0) {
    console.error("No package.json#devSite routes found under apps/* or packages/*.");
    process.exit(1);
  }

  const kept = foreignBlocks(new Set(routes.map((r) => r.host)));

  console.log(`devsite init — ${routes.length} route(s):`);
  for (const r of routes) console.log(`  ${r.host} → dev server's port at runtime  (${r.project})`);
  if (kept.length > 0) {
    console.log(`  + ${kept.length} block(s) from other repos kept verbatim`);
  }

  const content = renderCaddyfile(routes, kept);
  if (dryRun) {
    console.log(`\n--dry-run: would write ${CADDYFILE}:\n`);
    console.log(content);
    return;
  }

  console.log(`\nWriting ${CADDYFILE} + (re)starting the always-on Caddy service (needs sudo)…`);
  applyPrivileged(content);
  console.log("\nVerifying:");
  verify(routes);
  printChecklist(routes);
}

main().catch((err: unknown) => {
  console.error(`\ndevsite init failed: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(1);
});
